name: Deploy JSON to Azure

on:
  push:
    branches:
      - no trigger

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy JSON file to Azure
      uses: azure/cli@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az deployment group create \
            --resource-group <RESOURCE_GROUP_NAME> \
            --template-file ../kv.json
